---
title: "The Effect of Lobbying in Chicago"
author: "Claire Herdeman"
date: "1/23/2019"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(magrittr)
library(scales)
library(here)
library(readxl)
library(zoo)
library(ggrepel)
library(forecast)
source("utils.R")
source("load.R")
```

# Private Industries Use Lobbyists to Influence Government

```{r graph1, warning=FALSE, error=FALSE}
# Top 25 flag
top_20 <- compensation %>%
  group_by(CLIENT_NAME) %>%
  summarise(sum = sum(COMPENSATION_AMOUNT), cnt = n()) %>%
  arrange(desc(sum)) %>%
  slice(1:20) %>% 
  select(CLIENT_NAME)

compensation %<>% mutate(TOP20 = ifelse(CLIENT_NAME %in% top_20$CLIENT_NAME, "Yes", "No"))

# Two shades of the same color for bar colors, maybe don't label quarters, clarifty top20 labeling, simpler background,
# mark 25% on every bar
# Plotting
c <- compensation %>% 
  mutate(PERIOD_START = as.yearqtr(PERIOD_START, format = "%Y-%m-%d")) %>%
  #filter(PERIOD_START < as.Date('2018-07-01')) %>%
  group_by(TOP20, PERIOD_START) %>%
  summarise(sum = sum(COMPENSATION_AMOUNT), n = n()) %>%
  mutate(sum = sum/1000000) %>%
  ggplot(aes(PERIOD_START, sum)) +
    geom_col(aes(fill=factor(TOP20, levels=c("No","Yes")))) + 
    scale_y_continuous(label=dollar_format()) +
    scale_x_yearqtr(limits = c('2012 Q1', '2018 Q4'), format = "%YQ%q", n = 28) +
    scale_fill_manual(values=c("#9999ff", "#0000ff")) + 
    labs(title="The Top 20 Clients Pay ~25% of Lobbyist Compensation",
         subtitle="Total Quarterly Lobbyist Compensation, 2012 - 2018",
         caption="Source: City of Chicago Lobbyist Data, Compensation",
         x = "Time",
         y = "Total Lobbyist Compensation (in Millions)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.caption = element_text(hjust = 0),
        legend.box = 'horizontal',
        legend.position = c(0.46, 0.85)) +
  guides(fill=guide_legend(title="Top 20")) 

c + geom_point(data = compensation %>% 
  mutate(PERIOD_START = as.yearqtr(PERIOD_START, format = "%Y-%m-%d")) %>%
  #filter(PERIOD_START < as.Date('2018-07-01')) %>%
  group_by(PERIOD_START) %>%
  summarise(pct_25 = sum(COMPENSATION_AMOUNT) * .25/1000000, n = n()), aes(PERIOD_START, pct_25, color = '#ff0000')) +
  scale_color_identity(name = "25% Mark", 
                      labels = c(""), 
                      guide = "legend")


```

```{r graph2, fig.height = 5, fig.width = 7, warning=FALSE, error=FALSE}
# Map actual name to target name
#keys <- c()
#values <- c()
#dict <- setNames(as.list(values), key)
#NICK_NAME <- c()
# Legend on graph?
# lines of best fit by industry?
# brighter color palette, turn down the gray in the background
# increase font size on labeling
# try a bunch of different color schemes, look at recognizable graphics (NYT, Economist, plotyly, 538)
# Try putting all of the ones in? and then only highlight top 20? Needs more context

top <- compensation %>% 
  filter(TOP20 == 'Yes') %>% 
  group_by(CLIENT_NAME, CLIENT_INDUSTRY) %>%
  summarise(sum=sum(COMPENSATION_AMOUNT), n = n()) %>%
  mutate(sum = sum/1000000,
         INDUSTRY = if_else(CLIENT_INDUSTRY %in% c('HOSPITALITY / RESTAURANT', 'PUBLIC UTILITIES', 
                                                   'RETAIL', 'EDUCATION', 'RACING & WAGERING', 'TRANSPORTATION'), 
                            'OTHER INDUSTRY', CLIENT_INDUSTRY),
         NICK_NAME = if_else(str_detect(CLIENT_NAME, 'CVS'), 'CVS',
                      if_else(str_detect(CLIENT_NAME, 'CITI'), 'CITI',
                       if_else(str_detect(CLIENT_NAME, 'DELAWARE'), 'DELAWARE NORTH', 
                        if_else(str_detect(CLIENT_NAME, 'UNITED'), 'UPS', 
                         if_else(str_detect(CLIENT_NAME, 'HILTON'), 'HILTON', 
                          if_else(str_detect(CLIENT_NAME, 'DOMINION'), 'DOMINION VOTING', 
                           if_else(str_detect(CLIENT_NAME, 'PRESENCE'), 'PRESENCE HS', 
                            if_else(str_detect(CLIENT_NAME, 'ANDELL'), 'ANDELL', 
                             if_else(str_detect(CLIENT_NAME, 'SSP'), 'SSP AMERICA', 
                              if_else(str_detect(CLIENT_NAME, 'FAMILY'), 'FAMILY GUIDANCE CTRS',CLIENT_NAME)))))))))),
        NICK_NAME = tools::toTitleCase(tolower(NICK_NAME)))

t <-compensation %>% 
  filter(TOP20 == 'No') %>% 
  group_by(CLIENT_NAME) %>%
  summarise(sum=sum(COMPENSATION_AMOUNT), n = n()) %>%
  mutate(sum = sum/1000000) %>%
  ggplot() +
    geom_point(aes(n, sum), color = '#595959', size = 2, alpha = 0.4)

t + geom_point(data = top, aes(n, sum, color = INDUSTRY), size = 2, alpha = 0.7) +
    geom_text_repel(data = top, aes(n, sum, label = NICK_NAME), check_overlap = TRUE, size = 2, hjust = 0, nudge_x = 0.1) + 
    scale_y_continuous(label=dollar_format()) +
    xlim(0, 650) +
    labs(title="Tech Co's and Industry Associations are Among the Highest Paying Clients",
         subtitle="Compensation Payments to Lobbyists by Top 20 Clients, 2012 - 2018",
         caption="Source: City of Chicago Lobbyist Data, Compensation",
         x = "Number of Compensation Payments",
         y = "Total Compensation (in Millions)") +
    theme_minimal() +
    theme(plot.caption = element_text(hjust = 0),
          #legend.position="bottom",
          legend.text=element_text(size=6),
          legend.title=element_text(size=10),
          legend.position = c(0.8, 0.8))
  

```

```{r}
# try log scale? add annotation,
compensation %>% 
  filter(TOP20 == 'Yes') %>%
  group_by(LOBBYIST_NAME) %>% 
  summarise(sum = sum(COMPENSATION_AMOUNT), n = n()) %>% 
  mutate(sum = sum/1000000) %>%
  ggplot(aes(reorder(LOBBYIST_NAME, sum), sum)) +
  geom_point(stat = 'identity', size = 6) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_minimal()
  #arrange(desc(sum))

paid_by_top20 <- compensation %>% 
  filter(TOP20 == 'Yes') %>% group_by(LOBBYIST_NAME) %>% 
  summarise(sum = sum(COMPENSATION_AMOUNT), n = n()) %>% filter(sum >= 1000000) #arrange(desc(sum))
```

# Lobbying Activity

```{r graph3, warning=FALSE, error=FALSE}
# aggregate by year to show trend
# what happened  in 2017? why seasonality?
# fourier transformation - time to frequency domain
# axes labels, label quarter only, year underneath
# move legend onto plot

# Summarise data into necessary format
#act_summ <- 
  
activity %>% 
  mutate(year = format(PERIOD_START, '%Y'),
         PERIOD_START = as.yearqtr(PERIOD_START, format = "%Y-%m-%d")) %>%
  group_by(year, ACTION) %>%
  summarise(n = n()) %>%
  ggplot(aes(year, n)) +
    geom_line(aes(group=ACTION, color=ACTION), size = 1) +
  scale_x_yearqtr(limits = c('2012 Q1', '2018 Q4'), format = "%YQ%q", n = 28) +
  labs(title="Growth in administrative actions has outpaced others since 2016",
        subtitle="Quarterly Lobbying Actions by Type, 2012 - 2018",
        caption="Source: City of Chicago Lobbyist Data, Activity",
        x = "Time Period (Quarters)",
        y = "Number of Lobbying Actions") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.caption = element_text(hjust = 0)) +
  scale_fill_identity(name = "Difference", 
                      breaks = c("dark gray"), 
                      labels = c("Difference (# Admin - # Leg)"), 
                      guide = "legend")

#act_summ %>% group_by(year, ACTION) %>% summarise(avg = mean(n))

#diff <- data_frame(PERIOD_START = (act_summ %>% filter(ACTION == 'ADMINISTRATIVE'))$PERIOD_START, 
#                   n = (act_summ %>% filter(ACTION == 'ADMINISTRATIVE'))$n - 
#                     (act_summ %>% filter(ACTION == 'LEGISLATIVE'))$n) #%>%
#              #mutate(PERIOD_START = as.Date(PERIOD_START, '%m/%d/%Y'))
                  

# Plotting
ggplot(NULL, aes(PERIOD_START, n)) +
  geom_line(data=act_summ, aes(group=ACTION, color=ACTION), size = 1) +
  #geom_point(data=diff, aes(fill="dark gray"), size=3, shape=20) +
  scale_x_yearqtr(limits = c('2012 Q1', '2018 Q4'), format = "%YQ%q", n = 28) +
  labs(title="Growth in administrative actions has outpaced others since 2016",
        subtitle="Quarterly Lobbying Actions by Type, 2012 - 2018",
        caption="Source: City of Chicago Lobbyist Data, Activity",
        x = "Time",
        y = "Number of Lobbying Actions") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.caption = element_text(hjust = 0)) +
  scale_fill_identity(name = "Difference", 
                      breaks = c("dark gray"), 
                      labels = c("Difference (# Admin - # Leg)"), 
                      guide = "legend")

```

# Direct Influence on City Council

```{r councilmen, fig.height = 8, fig.width = 6, warning=FALSE, error=FALSE}
# demphasize names
# annotate burke
# dont color
# quartiles for amounts, maybe box?
# annotated legend at bottom of how box plot works - oconnor
# meh background gray
# repeate x axis on quartiles?
# highlight committee charis or finance commities?

council_last <- str_trim(toupper(str_extract(council$` Person Name`, '^[A-Za-z\']+')))
#council_last
f = ""
for (last in council_last[40:52]) {
  f <- paste(f, paste('ALDERMAN = if_else(str_detect(RECIPIENT, \'',last,'\'), \'',last,'\', ALDERMAN)', sep=""), ',', sep = "")
  }
#f

alderman_contributions <- contribution %>% 
  mutate(ALDERMAN = "") %>%
  mutate(ALDERMAN = if_else(str_detect(RECIPIENT, 'ARENA'), 'ARENA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'AUSTIN'), 'AUSTIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BEALE'), 'BEALE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BROOKINS'), 'BROOKINS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BURKE'), 'BURKE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BURNETT'), 'BURNETT', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CAPPLEMAN'), 'CAPPLEMAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CARDENAS'), 'CARDENAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'COCHRAN'), 'COCHRAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CURTIS'), 'CURTIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'DOWELL'), 'DOWELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'EMANUEL'), 'EMANUEL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'ERVIN'), 'ERVIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'FOULKES'), 'FOULKES', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HAIRSTON'), 'HAIRSTON', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HARRIS'), 'HARRIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HOPKINS'), 'HOPKINS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'KING'), 'KING', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'LAURINO'), 'LAURINO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'LOPEZ'), 'LOPEZ', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MALDONADO'), 'MALDONADO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MELL'), 'MELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MITCHELL'), 'MITCHELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MITTS'), 'MITTS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'JOE MOORE'), 'JOE MOORE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'DAVID MOORE'), 'DAVID MOORE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MORENO'), 'MORENO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MUNOZ'), 'MUNOZ', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'NAPOLITANO'), 'NAPOLITANO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, "O'CONNOR"), "O'CONNOR", ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, "O'SHEA"), "O'SHEA", ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'OSTERMAN'), 'OSTERMAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'PAWAR'), 'PAWAR', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'QUINN'), 'QUINN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'RAMIREZ'), 'RAMIREZ', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'REBOYRAS'), 'REBOYRAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'REILLY'), 'REILLY', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SADLOWSKI'), 'SADLOWSKI', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SANTIAGO'), 'SANTIAGO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SAWYER'), 'SAWYER', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SCOTT'), 'SCOTT', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SILVERSTEIN'), 'SILVERSTEIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SMITH'), 'SMITH', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SOLIS'), 'SOLIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SPOSATO'), 'SPOSATO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TABARES'), 'TABARES', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TALIAFERRO'), 'TALIAFERRO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'THOMPSON'), 'THOMPSON', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TUNNEY'), 'TUNNEY', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'VALENCIA'), 'VALENCIA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'VILLEGAS'), 'VILLEGAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'WAGUESPACK'), 'WAGUESPACK', ALDERMAN)
         ) %>% 
  filter(ALDERMAN != "" & ALDERMAN != "EMANUEL")
  
ald_totals <- alderman_contributions %>% 
  filter(CONTRIBUTION_DATE > as.Date('2014-12-31')) %>%
  group_by(ALDERMAN) %>% 
  summarise(sum = sum(AMOUNT), n = n()) %>%
  arrange(desc(sum))
                     
alderman_contributions %>% 
  filter(CONTRIBUTION_DATE > as.Date('2014-12-31')) %>%
  left_join(ald_totals, by = 'ALDERMAN') %>% #glimpse()
  ggplot() +
  geom_boxplot(aes(reorder(ALDERMAN, sum), AMOUNT), alpha = 0.8) + 
  coord_flip() +
  annotate("text", x = 'REILLY', y = 1600, label = "$153k") +
  theme_minimal()

#ald_totals
```

```{r lobbypay, fig.height = 6, fig.width = 6}
# shows more about who is and who isn't
# Bin lobbyists by location? octant of community areas
# sankey diagram

alderman_contributions %>% 
  mutate(paid_top20 = if_else(LOBBYIST_NAME %in% paid_by_top20$LOBBYIST_NAME, TRUE, FALSE))%>%
  filter(CONTRIBUTION_DATE > as.Date('2014-12-31') & paid_top20) %>%
  left_join(ald_totals, by = 'ALDERMAN') %>%
  group_by(ALDERMAN, LOBBYIST_NAME) %>% 
  summarise(sum = sum(AMOUNT), n = n()) %>%
  arrange(desc(sum)) %>% 
  ggplot() +
  geom_tile(aes(LOBBYIST_NAME, reorder(ALDERMAN, sum), fill = sum)) +
 # theme_minimal(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_minimal()
```

```{r}
#compensation %>% filter(str_detect(LOBBYIST_NAME, 'GATTUSO')) %>% group_by(CLIENT_NAME) %>% summarise(sum = sum(COMPENSATION_AMOUNT)) %>% arrange(desc(sum))
```
