---
title: "Assignment 1"
author: "Claire Herdeman"
date: "1/20/2019"
output: pdf_document
---

## Setup

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(magrittr)
library(scales)
library(here)
knitr::opts_chunk$set(echo = TRUE)
```

## Cleaning Functions
```{r functions, include=FALSE}

client_name_cleaning <- function(df) {
  if ("CLIENT_NAME" %in% colnames(df)) {
    
    df %<>% 
      mutate(CLIENT_NAME = str_trim(toupper(CLIENT_NAME), side = c("both")),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c("^S\\. ", "^S[^A-Z0-9]"), "SOUTH "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c(" S\\. ", " S[^A-Z0-9]"), " SOUTH "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c("^N\\. ", "^N[^A-Z0-9]"), "NORTH "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c(" N\\. ", " N[^A-Z0-9]"), " NORTH "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c("^E\\. ", "^E[^A-Z0-9]"), "EAST "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c(" E\\. ", " E[^A-Z0-9]"), " EAST "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c("^W\\. ", "^W[^A-Z0-9]"), "WEST "), 
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c(" W\\. ", " W[^A-Z0-9]"), " WEST "),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "ST\\.", "STREET"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "L.L.C.", "LLC"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, ", LLC", " LLC"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "L.L.P.", "LLP"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, ", LLP", " LLP"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "N.A.", "NA"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "INC\\.", "INC"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, ", INC", " INC"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, c("CORP\\. ", "CORP "), "CORPORATION "),
             # Specific hacks to group bigger players
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "^KPMG CORPORATE FINANCE LLC$", 
                                           "KPMG LLP"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "^PRICEWATERHOUSECOOPERS$", 
                                           "PRICEWATERHOUSECOOPERS LLP"),
             CLIENT_NAME = str_replace_all(CLIENT_NAME, "^UNITED PARCEL SERVICE INC$", 
                                           "UNITED PARCEL SERVICE"),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "JCDECAUX"), "JCDECAUX GROUP", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^CITIBANK"), "CITIBANK, NA", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^HERTZ"), "HERTZ GLOBAL", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^UNITED AIRLINES"), "UNITED AIRLINES", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^AIRBNB INC$"), "AIRBNB", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^SP PLUS CORP$"), "SP PLUS CORPORATION", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^CAR2GO NORTH A. LLC"), "CAR2GO NA LLC", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^LYFT INC$"), "LYFT", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^CVS HEALTH$"), "CVS CAREMARK CORP", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^NRG ENERGY SERVICES LLC$"), "NRG ENERGY INC",
                                   CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^PHILIPS LIGHTING NORTH AMERICA CORP$"), "PHILIPS LIGHTING",
                                   CLIENT_NAME),
             
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "CLEAR CHANNEL"), "CLEAR CHANNEL", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^THE BARRACK OBAMA FOUNAION"), 
                                              "THE BARACK OBAMA FOUNDATION", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "^AMAZON.COM$"), 
                                              "AMAZON", CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, '"I AM" TEMPLE OF CHICAGO INC'), 
                                   '"I AM" TEMPLE OF CHICAGO', CLIENT_NAME),
             CLIENT_NAME = if_else(str_detect(CLIENT_NAME, "1100 E 47TH STREET LLC"), 
                                   "1100 EAST 47TH STREET LLC", CLIENT_NAME)
            )
    
    return(df)
    
  } else {
    
    stop("Requires a column named CLIENT_NAME")
    
  }

}

```


## Load data

```{r load, include=FALSE}
# Client/Industry xwalk, keep name and primary industry only
cli_industry <- read_csv(here("data", "Clients_by_Industry.csv")) %>%
                  select('CLIENT_NAME' = 'CLIENT NAME',
                         'CLIENT_INDUSTRY' = 'CLIENT INDUSTRY') %>%
                  # add additional rows for missing clients
                  rbind(c("ARLINGTON PARK","RACING & WAGERING"),
                        c("CITIBANK, NORTH A.", "FINANCIAL / BANKING"),
                        c("HERTZ GLOBAL", "TRANSPORTATION"),
                        c("UNITED AIRLINES INC", "TRANSPORTATION"),
                        c("NORTH HIGHLAND", "OTHER"),
                        c("SONDER", "TOURISM & TRAVEL"),
                        c("ASSURED GUARANTY CORP.", "FINANCIAL / BANKING"),
                        c("TUK TUK CHICAGO", "TRANSPORTATION"),
                        c("BLACKSTONE ADMINISTRATIVE SERVICES L. P.", "FINANCIAL / BANKING"),
                        c("COMPUTER AID INC", "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES"),
                        c("LOGAN JONES LP", "OTHER"),
                        c("ASSOCIATION FOR ACCESSIBLE MEDICINES", "HEALTH/ MEDICAL / HOSPITAL"),
                        c("DELTA AIR LINES", "TRANSPORTATION"),
                        c("MEGABUS USA LLC", "TRANSPORTATION"),
                        c("WEC ENERGY GROUP INC", "PUBLIC UTILITIES"),
                        c("CONDUENT INC AND ITS AFFILIATES", "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES"),
                        c("LYFT INC", "TRANSPORTATION"),
                        c("CVS HEALTH", "HEALTH/ MEDICAL / HOSPITAL"),
                        c("NRG ENERGY SERVICES LLC", "PUBLIC UTILITIES"),
                        c("THE BARRACK OBAMA FOUNAION", "RELIGIOUS / NON-PROFIT ORGANIZATIONS"),
                        c("VENDOR ASSISTANCE PROGRAM LLC", "OTHER"),
                        c("DCI GROUP AZ LLC", "PUBLIC RELATIONS & ADVERTISING"),
                        c("VMWARE", "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES"),
                        c("SPOTHERO INC", "TRANSPORTATION"),
                        c("SENTINEL TECHNOLOGIES", "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES"),
                        c("ALLIEDBARTON SECURITY SERVICES LLC", "OTHER")
                        )
cli_industry <- client_name_cleaning(cli_industry)
cli_industry %<>% mutate(# Industry manipulations
                         CLIENT_INDUSTRY = str_trim(toupper(CLIENT_INDUSTRY), side = c("both")),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'KPMG'), 
                                                   "FINANCIAL / BANKING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CHICAGOLAND CHAMBER OF COMMERCE'), 
                                                   "TRADE & PROFESSIONAL ASSOCIATIONS", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'HONEYWELL INTERNATIONAL'), 
                                                   "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'PRICEWATERHOUSECOOPERS LLP'), 
                                                   "FINANCIAL / BANKING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'UNITED PARCEL SERVICE'), 
                                                   "TRANSPORTATION", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'FEDEX'), 
                                                   "TRANSPORTATION", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'JCDECAUX GROUP'), 
                                                   "MARKETING & SALES", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CITIBANK, NA'), 
                                                   "FINANCIAL / BANKING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'HERTZ'), 
                                                   "TRANSPORTATION", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'UNITED AIRLINES'), 
                                                   "TRANSPORTATION", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'AIRBNB'), 
                                                   "TOURISM & TRAVEL", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'PFIZER INC'), 
                                                   "HEALTH/ MEDICAL / HOSPITAL", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'LYFT'), 
                                                   "TRANSPORTATION", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CHICAGO NEIGHBORHOOD INITIATIVES'), 
                                                   "PUBLIC INTEREST", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CITY OF CHICAGO'), 
                                                   "GOVERNMENTAL UNITS", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CHICAGO DEPARTMENT OF AVIATION'), 
                                                   "TOURISM & TRAVEL", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'STEANS FAMILY FOUNAION'), 
                                                   "RELIGIOUS / NON-PROFIT ORGANIZATIONS", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'APPLE INC'), 
                                                   "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CASH AMERICA INTERNATIONAL'), 
                                                   "FINANCIAL / BANKING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'CLEAR CHANNEL'), 
                                                   "MARKETING & SALES", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'GROWTH ENERGY'), 
                                                   "TRADE & PROFESSIONAL ASSOCIATIONS", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'MUSEUM OF CONTEMPORARY ART'), 
                                                   "ARTS/ ENTERTAINMENT", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'PHILIPS LIGHTING'), 
                                                   "MANUFACTURING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'THE LEONIS GROUP'), 
                                                   "PUBLIC RELATIONS & ADVERTISING", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'RELIABLE ASPHALT COMPANY'), 
                                                   "OTHER", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_NAME, 'AMAZON'), 
                                                   "INFORMATION / TECHNOLOGY PRODUCTS OR SERVICES", CLIENT_INDUSTRY),
                         # Collapse industry categories
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_INDUSTRY, 'HEALTH'), 
                                                   "HEALTH", CLIENT_INDUSTRY),
                         CLIENT_INDUSTRY = if_else(str_detect(CLIENT_INDUSTRY, 'TECHNOLOGY'), 
                                                   "INFO/TECH PRODUCTS OR SERVICES", CLIENT_INDUSTRY)
                         ) %>%
                  # For the remaineder of client industries with multiple industries, pick one
                  arrange(CLIENT_NAME, CLIENT_INDUSTRY) %>%
                  distinct(CLIENT_NAME, .keep_all = TRUE)


# Lobbyist compensation
compensation <- read_csv(here("data", "Compensation.csv")) 
compensation <- client_name_cleaning(compensation)
compensation %<>% left_join(cli_industry, by="CLIENT_NAME") %>%
                  mutate(LOBBYIST_FIRST_NAME = toupper(LOBBYIST_FIRST_NAME),
                         LOBBYIST_MIDDLE_INITIAL = toupper(LOBBYIST_MIDDLE_INITIAL),
                         LOBBYIST_LAST_NAME = toupper(LOBBYIST_LAST_NAME),
                         LOBBYIST_NAME = stringr::str_c(LOBBYIST_FIRST_NAME, LOBBYIST_LAST_NAME, sep=" "),
                         PERIOD_START = as.Date(PERIOD_START, '%m/%d/%Y'),
                         PERIOD_END = as.Date(PERIOD_END, '%m/%d/%Y'),
                         CREATED_DATE = as.Date(CREATED_DATE, '%m/%d/%Y')
                         )

# Political contributions
contribution <- read_csv(here("data", "Contributions.csv")) %>%
                  mutate(RECIPIENT = toupper(RECIPIENT),
                         LOBBYIST_FIRST_NAME = toupper(LOBBYIST_FIRST_NAME),
                         LOBBYIST_LAST_NAME = toupper(LOBBYIST_LAST_NAME),
                         LOBBYIST_NAME = stringr::str_c(LOBBYIST_FIRST_NAME, LOBBYIST_LAST_NAME, sep=" "),
                         PERIOD_START = as.Date(PERIOD_START, '%m/%d/%Y'),
                         PERIOD_END = as.Date(PERIOD_END, '%m/%d/%Y'),
                         CONTRIBUTION_DATE = as.Date(CONTRIBUTION_DATE, '%m/%d/%Y'))

# Lobbying activity
activity <- read_csv(here("data", "Lobbying_Activity.csv")) 
activity <- client_name_cleaning(activity)
activity %<>% left_join(cli_industry, by="CLIENT_NAME") %>%
              mutate(ACTION = toupper(ACTION),
                     ACTION = if_else(str_detect(ACTION, 'BOTH'), 'BOTH', ACTION),
                     ACTION_SOUGHT = toupper(ACTION_SOUGHT),
                     DEPARTMENT = toupper(DEPARTMENT),
                     LOBBYIST_FIRST_NAME = toupper(LOBBYIST_FIRST_NAME),
                     LOBBYIST_MIDDLE_INITIAL = toupper(LOBBYIST_MIDDLE_INITIAL),
                     LOBBYIST_LAST_NAME = toupper(LOBBYIST_LAST_NAME),
                     LOBBYIST_NAME = stringr::str_c(LOBBYIST_FIRST_NAME, LOBBYIST_LAST_NAME, sep=" "),
                     PERIOD_START = as.Date(PERIOD_START, '%m/%d/%Y'),
                     PERIOD_END = as.Date(PERIOD_END, '%m/%d/%Y')
                     )

# Lobbyist info
lobbyists <- read_csv(here("data", "Lobbyists.csv")) %>%
               mutate(SALUTATION = toupper(SALUTATION),
                      FIRST_NAME = toupper(FIRST_NAME),
                      MIDDLE_INITIAL = toupper(MIDDLE_INITIAL),
                      LAST_NAME = toupper(LAST_NAME),
                      SUFFIX = toupper(SUFFIX),
                      EMPLOYER_NAME = toupper(EMPLOYER_NAME),
                      LOBBYIST_NAME = stringr::str_c(FIRST_NAME, LAST_NAME, sep=" ")
                     ) %>% 
              distinct()

# Lobbyist/Employer/Client combos
combinations <- read_csv(here("data", "Lobbyist__Employer__Client_Combinations.csv")) 
combinations <- client_name_cleaning(combinations)
combinations %<>% left_join(cli_industry, by="CLIENT_NAME") %>%
                  mutate(LOBBYIST_SALUTATION = toupper(LOBBYIST_SALUTATION),
                         LOBBYIST_FIRST_NAME = toupper(LOBBYIST_FIRST_NAME),
                         LOBBYIST_MIDDLE_INITIAL = toupper(LOBBYIST_MIDDLE_INITIAL),
                         LOBBYIST_LAST_NAME = toupper(LOBBYIST_LAST_NAME),
                         LOBBYIST_SUFFIX = toupper(LOBBYIST_SUFFIX),
                         EMPLOYER_NAME = toupper(EMPLOYER_NAME),
                         LOBBYIST_NAME = stringr::str_c(LOBBYIST_FIRST_NAME, LOBBYIST_LAST_NAME, sep=" "))
```

# Graph 1

```{r graph1}
# Top 25 flag
top_20 <- compensation %>%
  group_by(CLIENT_NAME) %>%
  summarise(sum = sum(COMPENSATION_AMOUNT), cnt = n()) %>%
  arrange(desc(sum)) %>%
  slice(1:20) %>% 
  select(CLIENT_NAME)

compensation %<>% mutate(TOP20 = ifelse(CLIENT_NAME %in% top_20$CLIENT_NAME, "Yes", "No"))

# Plotting
compensation %>%
  filter(PERIOD_START < as.Date('2018-07-01')) %>% 
  group_by(TOP20, PERIOD_START) %>%
  summarise(sum = sum(COMPENSATION_AMOUNT), n = n()) %>%
  mutate(sum = sum/1000) %>%
  ggplot(aes(PERIOD_START, sum)) +
    geom_col(aes(fill=factor(TOP20, levels=c("No","Yes")))) + 
    scale_y_continuous(label=dollar_format(), sec.axis = sec_axis(~.+0, label=dollar_format())) +
    scale_x_date(date_breaks='3 months') +
    scale_fill_manual(values=c("#999999", "#56B4E9")) + 
    labs(title="The Top 20 Clients Pay ~25% of Lobbyist Compensation",
         subtitle="Total Quarterly Lobbyist Compensation, 2012 - 2018",
         caption="Source: City of Chicago Lobbyist Data, Compensation",
         x = "Time Period (Quarters)",
         y = "Total Lobbyist Compensation (in Thousands)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.caption = element_text(hjust = 0)) +
  guides(fill=guide_legend(title="Top 20"))
  
```

# Graph 2

```{r graph2}
compensation %>% 
  filter(TOP20 == 'Yes') %>% 
  group_by(CLIENT_NAME, CLIENT_INDUSTRY) %>%
  summarise(sum=sum(COMPENSATION_AMOUNT), n = n()) %>%
  mutate(sum = sum/1000) %>%
  ggplot() +
    geom_point(aes(n, sum), size = 2, alpha = 0.7) +
    geom_text(aes(n, sum, label = CLIENT_NAME), check_overlap = TRUE, size = 2, hjust = 0, vjust = "inward", nudge_x = 0.5) +
    scale_y_continuous(label=dollar_format()) +
    xlim(0, 650) +
    labs(title="Tech Co's and Industry Associations are Among the Highest Paying Clients",
         subtitle="Number and Size of Compensation Payments to Lobbyists by Top 20 Clients, 2012 - 2018",
         caption="Source: City of Chicago Lobbyist Data, Compensation",
         x = "Number of Compensation Payments",
         y = "Amount of Compensation Payemnts") +
    theme(plot.caption = element_text(hjust = 0))

```

# Graph 3

```{r graph3}
# Summarise data into necessary format
act_summ <- activity %>% 
  group_by(PERIOD_START, ACTION) %>%
  summarise(n = n()) 

diff <- data_frame(PERIOD_START = (act_summ %>% filter(ACTION == 'ADMINISTRATIVE'))$PERIOD_START, 
                   n = (act_summ %>% filter(ACTION == 'ADMINISTRATIVE'))$n - 
                     (act_summ %>% filter(ACTION == 'LEGISLATIVE'))$n) %>%
              mutate(PERIOD_START = as.Date(PERIOD_START, '%m/%d/%Y'))
                  

# Plotting
ggplot(NULL, aes(PERIOD_START, n)) +
  geom_line(data=act_summ, aes(group=ACTION, color=ACTION), size = 1) +
  geom_point(data=diff, aes(fill="dark gray"), size=3, shape=20) +
  scale_x_date(date_breaks='3 months') +
  labs(title="Growth in administrative actions has outpaced others since 2016",
        subtitle="Quarterly Lobbying Actions by Type, 2012 - 2018",
        caption="Source: City of Chicago Lobbyist Data, Activity",
        x = "Time Period (Quarters)",
        y = "Number of Lobbying Actions") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.caption = element_text(hjust = 0)) +
  scale_fill_identity(name = "Difference", 
                      breaks = c("dark gray"), 
                      labels = c("Difference (# Admin - # Leg)"), 
                      guide = "legend")

```